name: 🚀 Update Merged Playlist 📺

on:
  schedule:
    - cron: '*/15 * * * *'  # ⏰ Every 30 minutes (UTC)
  workflow_dispatch:        # 🔘 Manual trigger

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install required Python dependency
        run: pip install requests

      - name: Fetch M3U8
        run: uv run M3U8/fetch.py

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "update M3U8"
          file_pattern: "M3U8/TV.m3u8"
          commit_author: "GitHub Actions Bot <actions@github.com>"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
